###
POST http://localhost:3001/game
content-type: application/json

{
  "game": {
    "result": "win",
    "moves": [
      {
        "player": "user",
        "box": 4
      }
    ]
  }
}

###
GET http://localhost:3001/game
